- name: Install Apache
  ansible.builtin.yum:
    name: 
      - httpd
      - firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Start Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Backup httpd.conf
  ansible.builtin.fetch:
    src: /etc/httpd/conf/httpd.conf
    dest: /tmp/httpd.conf.backup
    flat: true

- name: Change Apache listen port to 88
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    line: Listen 88

- name: Allow Apache to use port 88 in SELinux
  ansible.builtin.command: semanage port -m -t http_port_t -p tcp 88
  args:
    warn: false
  ignore_errors: true

- name: Ensure firewalld allows port 88
  ansible.posix.firewalld:
    port: 88/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Restart Apache
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
